import{BadRequestException,Injectable,NotFoundException}from'@nestjs/common';import{Prisma}from'@ffai/database';import type{AuthUser}from'../auth/auth.types';import{PrismaService}from'../prisma/prisma.service';import type{CreatePurchaseItemDto,CreatePurchaseOrderDto,CreateSupplierDto,ReceivePurchaseItemDto,ScmListQueryDto}from'./dto/scm.dto';
@Injectable()export class ScmService{constructor(private readonly prisma:PrismaService){}
async suppliers(user:AuthUser,query:ScmListQueryDto){const where:Prisma.SupplierWhereInput={organizationId:user.organizationId,...(query.keyword?{OR:[{supplierNo:{contains:query.keyword,mode:'insensitive'}},{name:{contains:query.keyword,mode:'insensitive'}},{shortName:{contains:query.keyword,mode:'insensitive'}}]}:{})};const[items,total]=await this.prisma.$transaction([this.prisma.supplier.findMany({where,skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{updatedAt:'desc'},include:{_count:{select:{purchaseOrders:true}}}}),this.prisma.supplier.count({where})]);return{items,total,page:query.page,pageSize:query.pageSize}}
async createSupplier(user:AuthUser,input:CreateSupplierDto){return this.prisma.$transaction(async tx=>{const supplierNo=input.supplierNo?.trim()||await this.nextNumber(tx,user.organizationId,'SUPPLIER');return tx.supplier.create({data:{...input,supplierNo,organizationId:user.organizationId,createdById:user.sub}})})}
async orders(user:AuthUser,query:ScmListQueryDto){const scope=this.scope(user);const where:Prisma.PurchaseOrderWhereInput={organizationId:user.organizationId,...scope,...(query.status?{status:query.status}:{}),...(query.keyword?{OR:[{purchaseOrderNo:{contains:query.keyword,mode:'insensitive'}},{supplier:{name:{contains:query.keyword,mode:'insensitive'}}}]}:{})};const[items,total,groups]=await this.prisma.$transaction([this.prisma.purchaseOrder.findMany({where,skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{updatedAt:'desc'},include:{supplier:{select:{id:true,supplierNo:true,name:true}},buyer:{select:{displayName:true}},salesOrder:{select:{id:true,orderNo:true,title:true}},_count:{select:{items:true}}}}),this.prisma.purchaseOrder.count({where}),this.prisma.purchaseOrder.groupBy({by:['status'],where:{organizationId:user.organizationId,...scope},_count:true,orderBy:{status:'asc'}})]);return{items,total,page:query.page,pageSize:query.pageSize,summary:Object.fromEntries(groups.map(g=>[g.status,g._count]))}}
async detail(user:AuthUser,id:string){const order=await this.prisma.purchaseOrder.findFirst({where:{id,organizationId:user.organizationId,...this.scope(user)},include:{supplier:true,buyer:{select:{id:true,displayName:true}},approvedBy:{select:{displayName:true}},salesOrder:{select:{id:true,orderNo:true,title:true}},items:{orderBy:[{sort:'asc'},{lineNo:'asc'}],include:{product:{select:{productNo:true,name:true}},sku:{select:{skuCode:true,name:true}}}}}});if(!order)throw new NotFoundException('采购单不存在或不在当前数据范围内');return order}
async createOrder(user:AuthUser,input:CreatePurchaseOrderDto){const supplier=await this.prisma.supplier.findFirst({where:{id:input.supplierId,organizationId:user.organizationId,status:'ACTIVE'}});if(!supplier)throw new BadRequestException('供应商不存在或不可用');if(input.salesOrderId){const so=await this.prisma.salesOrder.findFirst({where:{id:input.salesOrderId,organizationId:user.organizationId,...this.orderScope(user)}});if(!so)throw new BadRequestException('销售订单不存在或不在数据范围内')}return this.prisma.$transaction(async tx=>{const purchaseOrderNo=await this.nextNumber(tx,user.organizationId,'PURCHASE_ORDER');return tx.purchaseOrder.create({data:{organizationId:user.organizationId,purchaseOrderNo,supplierId:input.supplierId,salesOrderId:input.salesOrderId,expectedArrivalAt:input.expectedArrivalAt?new Date(input.expectedArrivalAt):undefined,notes:input.notes,buyerId:user.sub,createdById:user.sub}})})}
async addItem(user:AuthUser,id:string,input:CreatePurchaseItemDto){const order=await this.detail(user,id);if(order.status!=='DRAFT')throw new BadRequestException('只有草稿采购单可以编辑');if(!input.productId&&!input.description)throw new BadRequestException('请选择产品或填写采购内容');const product=input.productId?await this.prisma.product.findFirst({where:{id:input.productId,organizationId:user.organizationId,deletedAt:null}}):null;if(input.productId&&!product)throw new BadRequestException('产品不存在');const sku=input.skuId?await this.prisma.productSku.findFirst({where:{id:input.skuId,productId:input.productId}}):null;const quantity=new Prisma.Decimal(input.quantity),unitPrice=new Prisma.Decimal(input.unitPrice??sku?.factoryPrice??product?.factoryPrice??0),taxRate=new Prisma.Decimal(input.taxRate??0),amount=quantity.mul(unitPrice).toDecimalPlaces(2);await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`purchase-item:${id}`}))`;const max=await tx.purchaseOrderItem.aggregate({where:{purchaseOrderId:id},_max:{lineNo:true}});await tx.purchaseOrderItem.create({data:{purchaseOrderId:id,lineNo:(max._max.lineNo??0)+1,productId:input.productId,skuId:input.skuId,description:input.description||sku?.name||product?.name||'采购项目',specification:input.specification,quantity,unit:input.unit||product?.unit||'项',unitPrice,taxRate,amount,sort:((max._max.lineNo??0)+1)*10}})});await this.recalculate(id);return this.detail(user,id)}
async submit(user:AuthUser,id:string){const o=await this.detail(user,id);if(o.status!=='DRAFT'||!o.items.length)throw new BadRequestException('只有包含明细的草稿采购单可以提交');return this.prisma.purchaseOrder.update({where:{id},data:{status:'PENDING_APPROVAL'}})}
async approve(user:AuthUser,id:string){const o=await this.detail(user,id);if(o.status!=='PENDING_APPROVAL')throw new BadRequestException('只有待审批采购单可以审批');return this.prisma.purchaseOrder.update({where:{id},data:{status:'APPROVED',approvedById:user.sub,approvedAt:new Date()}})}
async place(user:AuthUser,id:string){const o=await this.detail(user,id);if(o.status!=='APPROVED')throw new BadRequestException('只有已审批采购单可以下单');return this.prisma.purchaseOrder.update({where:{id},data:{status:'ORDERED',orderedAt:new Date()}})}
async receive(user:AuthUser,id:string,itemId:string,input:ReceivePurchaseItemDto){void user;void id;void itemId;void input;throw new BadRequestException('WMS 已启用，请在仓储库存中心选择入库库位并完成采购入库')}
private scope(user:AuthUser):Prisma.PurchaseOrderWhereInput{if(user.dataScopes.includes('ALL')||user.dataScopes.includes('COMPANY'))return{};return{OR:[{buyerId:user.sub},{salesOrder:{OR:[{ownerId:user.sub},{project:{members:{some:{userId:user.sub}}}}]}}]}}
private orderScope(user:AuthUser):Prisma.SalesOrderWhereInput{if(user.dataScopes.includes('ALL')||user.dataScopes.includes('COMPANY'))return{};return{OR:[{ownerId:user.sub},{project:{members:{some:{userId:user.sub}}}}]}}
private async recalculate(id:string){const o=await this.prisma.purchaseOrder.findUniqueOrThrow({where:{id},include:{items:true}});const subtotal=o.items.reduce((s,i)=>s.add(i.amount),new Prisma.Decimal(0));const tax=o.items.reduce((s,i)=>s.add(i.amount.mul(i.taxRate)),new Prisma.Decimal(0)).toDecimalPlaces(2);await this.prisma.purchaseOrder.update({where:{id},data:{subtotal,taxAmount:tax,totalAmount:subtotal.add(tax)}})}
private async nextNumber(tx:Prisma.TransactionClient,organizationId:string,code:string){await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`${organizationId}:${code}`}))`;const r=await tx.businessNumberRule.findUnique({where:{organizationId_code:{organizationId,code}}});if(!r||!r.active)throw new NotFoundException(`业务编号规则 ${code} 不存在`);const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replaceAll('-','');const n=r.currentDate===date?r.currentValue+1:1;await tx.businessNumberRule.update({where:{id:r.id},data:{currentDate:date,currentValue:n}});return`${r.prefix}-${date}-${String(n).padStart(r.sequenceLength,'0')}`}}
