'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { api, type Principal } from '@/lib/api';
import { AppShell } from './AppShell';

type Profile=Principal&{employeeNo?:string;jobTitle?:string;remark?:string;status:string;passwordChangedAt?:string;lastLoginAt?:string;organization:{code:string;name:string};roles:{role:{id:string;code:string;name:string;dataScope:string}}[];orgUnits:{isPrimary:boolean;orgUnit:{id:string;code:string;name:string;path:string}}[]};

export function AccountPage(){
 const router=useRouter();const params=useSearchParams();const [profile,setProfile]=useState<Profile>();const [info,setInfo]=useState({displayName:'',phone:'',email:''});const [password,setPassword]=useState({currentPassword:'',newPassword:'',confirmPassword:''});const [notice,setNotice]=useState('');const [error,setError]=useState('');
 async function load(){try{const data=await api<Profile>('/me');setProfile(data);setInfo({displayName:data.displayName,phone:data.phone??'',email:data.email??''})}catch(e){setError(e instanceof Error?e.message:'读取账号失败')}}
 useEffect(()=>{void load()},[]);
 async function saveProfile(e:FormEvent){e.preventDefault();setError('');setNotice('');try{await api('/me/profile',{method:'PATCH',body:JSON.stringify(info)});setNotice('账号资料已更新');await load()}catch(err){setError(err instanceof Error?err.message:'保存失败')}}
 async function change(e:FormEvent){e.preventDefault();setError('');setNotice('');if(password.newPassword!==password.confirmPassword){setError('两次输入的新密码不一致');return}try{await api('/me/change-password',{method:'POST',body:JSON.stringify({currentPassword:password.currentPassword,newPassword:password.newPassword})});sessionStorage.removeItem('ffai_access_token');router.replace('/login?password=changed')}catch(err){setError(err instanceof Error?err.message:'修改密码失败')}}
 return <AppShell title="账号中心" subtitle="管理个人联系方式和登录密码；角色、组织和权限由管理员统一维护。">
  {(params.get('password')==='required'||profile?.mustChangePassword)&&<div className="password-required"><b>需要修改临时密码</b><span>为了账号安全，修改成功后需使用新密码重新登录。</span></div>}{notice&&<div className="success block">{notice}</div>}{error&&<div className="error block">{error}</div>}
  <div className="account-grid"><section className="account-card profile-overview"><div className="profile-avatar">{profile?.displayName?.slice(0,1)??'…'}</div><h2>{profile?.displayName??'正在读取'}</h2><p>@{profile?.username}</p><div className="profile-facts"><span><small>企业</small><b>{profile?.organization.name??'—'}</b></span><span><small>工号</small><b>{profile?.employeeNo??'未设置'}</b></span><span><small>职务</small><b>{profile?.jobTitle??'未设置'}</b></span><span><small>账号状态</small><b>{profile?.status??'—'}</b></span><span><small>最近登录</small><b>{profile?.lastLoginAt?new Date(profile.lastLoginAt).toLocaleString('zh-CN'):'从未登录'}</b></span><span><small>上次改密</small><b>{profile?.passwordChangedAt?new Date(profile.passwordChangedAt).toLocaleDateString('zh-CN'):'未记录'}</b></span></div><h3>我的角色</h3><div className="tag-list">{profile?.roles.map(x=><em key={x.role.id}>{x.role.name} · {x.role.dataScope}</em>)}</div><h3>所属组织</h3><div className="org-membership">{profile?.orgUnits.map(x=><span key={x.orgUnit.id}><b>{x.orgUnit.name}</b><small>{x.orgUnit.path}{x.isPrimary?' · 主组织':''}</small></span>)}</div></section>
   <div><section className="account-card"><h2>个人资料</h2><p>姓名、手机号和邮箱可自行更新，账号与工号需联系管理员。</p><form className="access-form" onSubmit={saveProfile}><label>登录账号<input disabled value={profile?.username??''}/></label><label>姓名 / 显示名<input required value={info.displayName} onChange={e=>setInfo({...info,displayName:e.target.value})}/></label><label>手机号<input value={info.phone} onChange={e=>setInfo({...info,phone:e.target.value})}/></label><label>邮箱<input type="email" value={info.email} onChange={e=>setInfo({...info,email:e.target.value})}/></label><button className="primary">保存个人资料</button></form></section>
   <section className="account-card password-card"><h2>修改登录密码</h2><p>密码至少 8 位。修改后会撤销所有设备上的登录会话。</p><form className="access-form" onSubmit={change}><label>当前密码<input required minLength={8} type="password" autoComplete="current-password" value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})}/></label><label>新密码<input required minLength={8} type="password" autoComplete="new-password" value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})}/></label><label>再次输入新密码<input required minLength={8} type="password" autoComplete="new-password" value={password.confirmPassword} onChange={e=>setPassword({...password,confirmPassword:e.target.value})}/></label><button className="primary">修改密码并重新登录</button></form></section></div>
  </div>
 </AppShell>
}
