'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, type Principal } from '@/lib/api';
import { AppShell } from './AppShell';

type Metrics = { generatedAt: string; customer: { customers: number; leads: number; wonLeads: number; leadWinRate: number; projects: number }; sales: { count: number; totalAmount: number; paidAmount: number; quotationCount: number; quotationValue: number; statuses: Record<string, number> }; operations: { activeProduction: number; overdueWorkOrders: number; stockBalances: number; unavailableStock: number }; finance: { receivableCount: number; receivableOutstanding: number; payableCount: number; payableOutstanding: number; cashIn: number; cashOut: number }; fulfillment: { openShipments: number; openInstallations: number; openAfterSales: number; urgentAfterSales: number }; execution: { openTasks: number; overdueTasks: number; activeAlerts: number; criticalAlerts: number } };
type Insight = { id: string; type: string; status: string; severity: string; title: string; summary: string; recommendation: string; evidence: Record<string, number>; generatedAt: string };
const money = (value: number) => new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY', maximumFractionDigits: 0 }).format(value);
const orderNames: Record<string, string> = { CONFIRMED: '已确认', PLANNING: '待计划', IN_PRODUCTION: '生产中', READY_TO_SHIP: '待发货', SHIPPED: '已发货', INSTALLED: '已安装', COMPLETED: '已完成' };
const empty: Metrics = { generatedAt: '', customer: { customers: 0, leads: 0, wonLeads: 0, leadWinRate: 0, projects: 0 }, sales: { count: 0, totalAmount: 0, paidAmount: 0, quotationCount: 0, quotationValue: 0, statuses: {} }, operations: { activeProduction: 0, overdueWorkOrders: 0, stockBalances: 0, unavailableStock: 0 }, finance: { receivableCount: 0, receivableOutstanding: 0, payableCount: 0, payableOutstanding: 0, cashIn: 0, cashOut: 0 }, fulfillment: { openShipments: 0, openInstallations: 0, openAfterSales: 0, urgentAfterSales: 0 }, execution: { openTasks: 0, overdueTasks: 0, activeAlerts: 0, criticalAlerts: 0 } };

export function AnalyticsPage() {
  const [data, setData] = useState<Metrics>(empty); const [insights, setInsights] = useState<Insight[]>([]); const [me, setMe] = useState<Principal | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [metrics, profile] = await Promise.all([api<Metrics>('/analytics/dashboard'), api<Principal>('/me')]); setData(metrics); setMe(profile); const readable = profile.permissions.includes('ai.insight.read'); setInsights(readable ? await api<Insight[]>('/analytics/insights?status=ACTIVE') : []); } catch (e) { setError(e instanceof Error ? e.message : '读取经营分析失败'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const maxOrder = useMemo(() => Math.max(1, ...Object.values(data.sales.statuses)), [data.sales.statuses]);
  async function snapshot() { try { await api('/analytics/snapshots', { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '生成快照失败'); } }
  async function generate() { try { await api('/analytics/insights/generate', { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '生成洞察失败'); } }
  async function dismiss(item: Insight) { try { await api(`/analytics/insights/${item.id}/dismiss`, { method: 'PATCH' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '忽略洞察失败'); } }
  return <AppShell title="BI / AI 智能决策中心" subtitle="统一聚合客户、订单、生产、库存、财务与履约指标；所有智能建议都展示可追溯业务证据。">
    <div className="analytics-actions"><span>实时口径 · {data.generatedAt ? new Date(data.generatedAt).toLocaleString('zh-CN') : '正在计算'}</span><div>{me?.permissions.includes('analytics.snapshot.generate') && <button onClick={() => void snapshot()}>保存今日快照</button>}{me?.permissions.includes('ai.insight.generate') && <button className="action" onClick={() => void generate()}>生成智能洞察</button>}</div></div>
    {error && <div className="error block">{error}</div>}
    <div className="analytics-kpis"><article><span>有效订单金额</span><strong>{money(data.sales.totalAmount)}</strong><small>{data.sales.count} 个有效订单</small></article><article><span>应收余额</span><strong className={data.finance.receivableOutstanding ? 'negative' : ''}>{money(data.finance.receivableOutstanding)}</strong><small>{data.finance.receivableCount} 笔应收</small></article><article><span>净现金流</span><strong>{money(data.finance.cashIn - data.finance.cashOut)}</strong><small>流入 {money(data.finance.cashIn)} · 流出 {money(data.finance.cashOut)}</small></article><article><span>交付与执行风险</span><strong className={data.execution.criticalAlerts ? 'negative' : ''}>{data.execution.criticalAlerts + data.execution.overdueTasks}</strong><small>严重预警 + 超期任务</small></article></div>
    <div className="analytics-grid"><section className="analytics-panel"><header><div><h3>订单状态结构</h3><p>当前有效订单在履约链上的分布</p></div><b>{data.sales.count}</b></header><div className="status-bars">{Object.entries(data.sales.statuses).map(([key, value]) => <article key={key}><span>{orderNames[key] ?? key}</span><div><i style={{ width: `${value / maxOrder * 100}%` }} /></div><b>{value}</b></article>)}</div></section><section className="analytics-panel"><header><div><h3>全链经营脉搏</h3><p>来自业务中心的实时统计</p></div></header><div className="pulse-grid"><article><b>{data.customer.customers}</b><span>客户</span></article><article><b>{(data.customer.leadWinRate * 100).toFixed(0)}%</b><span>线索赢单率</span></article><article><b>{data.operations.activeProduction}</b><span>在制生产单</span></article><article><b>{data.operations.unavailableStock}</b><span>零可用库存</span></article><article><b>{data.fulfillment.openAfterSales}</b><span>未闭环售后</span></article><article><b>{data.execution.openTasks}</b><span>未完成任务</span></article></div></section></div>
    <div className="section-title analytics-title"><div><h3>可解释智能洞察</h3><p>基于当前数据库指标生成，建议不替代人工审批和经营判断。</p></div></div>
    <div className="insight-grid">{insights.map((item) => <article key={item.id} className={`severity-${item.severity.toLowerCase()}`}><header><span>{item.type}</span><em>{item.severity}</em></header><h3>{item.title}</h3><p>{item.summary}</p><div><b>建议</b><span>{item.recommendation}</span></div><footer><small>生成于 {new Date(item.generatedAt).toLocaleString('zh-CN')}</small>{me?.permissions.includes('ai.insight.manage') && <button onClick={() => void dismiss(item)}>忽略</button>}</footer></article>)}</div>
    {!loading && !insights.length && <div className="empty">尚未生成活动洞察，请由获授权角色运行智能分析。</div>}{loading && <div className="empty">正在计算跨中心经营指标…</div>}
  </AppShell>;
}
