'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AppShell } from './AppShell';
import { api, withQuery } from '@/lib/api';

type Customer = { id:string; customerNo:string; name:string; shortName?:string; type:string; status:string; phone?:string; source?:string; level?:string; tags:string[]; updatedAt:string; owner:{displayName:string}; orgUnit:{name:string}; contacts?:Contact[]; activities?:Activity[]; _count:{contacts:number;activities:number} };
type Contact = { id:string;name:string;title?:string;phone?:string;isPrimary:boolean };
type Activity = { id:string;type:string;content:string;occurredAt:string;createdBy:{displayName:string} };
type ListResult = { items:Customer[];total:number;summary:Record<string,number> };
const statusName:Record<string,string>={PROSPECT:'潜在客户',ACTIVE:'合作中',INACTIVE:'暂缓',BLACKLISTED:'已停用'};
const typeName:Record<string,string>={INDIVIDUAL:'个人客户',COMPANY:'企业客户',DEALER:'经销商',DESIGNER:'合作设计师'};

export function CrmCustomersPage(){
  const [data,setData]=useState<ListResult>({items:[],total:0,summary:{}}); const [keyword,setKeyword]=useState(''); const [status,setStatus]=useState('');
  const [showCreate,setShowCreate]=useState(false); const [selected,setSelected]=useState<Customer|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api<ListResult>(withQuery('/crm/customers',{keyword,status})));}catch(e){setError(e instanceof Error?e.message:'读取失败');}finally{setLoading(false)}},[keyword,status]);
  useEffect(()=>{void load()},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));try{await api('/crm/customers',{method:'POST',body:JSON.stringify(values)});form.reset();setShowCreate(false);await load()}catch(e){setError(e instanceof Error?e.message:'新增失败')}}
  async function open(id:string){try{setSelected(await api<Customer>(`/crm/customers/${id}`))}catch(e){setError(e instanceof Error?e.message:'读取失败')}}
  async function follow(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));try{await api(`/crm/customers/${selected.id}/activities`,{method:'POST',body:JSON.stringify(values)});form.reset();await open(selected.id);await load()}catch(e){setError(e instanceof Error?e.message:'保存失败')}}
  return <AppShell title="客户管理" subtitle="客户、联系人与跟进记录共用同一份客户资产。">
    <div className="crm-stats"><article><span>客户总数</span><strong>{data.total}</strong></article><article><span>合作中</span><strong>{data.summary.ACTIVE??0}</strong></article><article><span>潜在客户</span><strong>{data.summary.PROSPECT??0}</strong></article><article><span>本次列表</span><strong>{data.items.length}</strong></article></div>
    <div className="crm-toolbar"><div className="search-box"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索编号、名称、电话或联系人"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{Object.entries(statusName).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div><button className="action" onClick={()=>setShowCreate(true)}>＋ 新增客户</button></div>
    {error&&<div className="error block">{error}</div>}
    <div className="crm-table"><table><thead><tr><th>客户</th><th>类型 / 等级</th><th>联系电话</th><th>来源</th><th>负责人</th><th>协同记录</th><th>状态</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id} onClick={()=>void open(item.id)}><td><b>{item.name}</b><small>{item.customerNo}</small></td><td>{typeName[item.type]} · {item.level??'未分级'}</td><td>{item.phone??'—'}</td><td>{item.source??'—'}</td><td>{item.owner.displayName}<small>{item.orgUnit.name}</small></td><td>{item._count.contacts} 位联系人 · {item._count.activities} 次跟进</td><td><span className={`state ${item.status.toLowerCase()}`}>{statusName[item.status]}</span></td></tr>)}</tbody></table>{loading&&<div className="empty">正在读取客户…</div>}{!loading&&!data.items.length&&<div className="empty">暂无符合条件的客户</div>}</div>
    {showCreate&&<div className="drawer-mask" onMouseDown={()=>setShowCreate(false)}><section className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowCreate(false)}>×</button><p className="eyebrow">NEW CUSTOMER</p><h2>建立客户档案</h2><form className="crm-form" onSubmit={create}><label>客户名称<input name="name" required placeholder="企业或个人名称"/></label><div><label>客户类型<select name="type" defaultValue="COMPANY"><option value="COMPANY">企业客户</option><option value="INDIVIDUAL">个人客户</option><option value="DEALER">经销商</option><option value="DESIGNER">合作设计师</option></select></label><label>客户等级<select name="level" defaultValue="B"><option>A</option><option>B</option><option>C</option></select></label></div><label>联系电话<input name="phone" placeholder="手机号或座机"/></label><label>来源<input name="source" placeholder="官网、转介绍、展会等"/></label><label>备注<textarea name="notes" rows={4}/></label><button className="primary">保存客户档案</button></form></section></div>}
    {selected&&<div className="drawer-mask" onMouseDown={()=>setSelected(null)}><section className="drawer wide" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.customerNo}</p><h2>{selected.name}</h2><div className="detail-meta"><span>{typeName[selected.type]}</span><span>{selected.phone??'未留电话'}</span><span>{selected.owner.displayName} · {selected.orgUnit.name}</span></div><h3>联系人</h3><div className="contact-list">{selected.contacts?.map(c=><div key={c.id}><b>{c.name}{c.isPrimary&&<em>主要</em>}</b><span>{c.title??'联系人'} · {c.phone??'未留电话'}</span></div>)}{!selected.contacts?.length&&<p>暂无联系人</p>}</div><h3>新增跟进</h3><form className="follow-form" onSubmit={follow}><select name="type" defaultValue="CALL"><option value="CALL">电话</option><option value="MESSAGE">微信/消息</option><option value="VISIT">拜访</option><option value="MEETING">会议</option><option value="NOTE">备注</option></select><textarea name="content" required placeholder="记录沟通内容、客户关注点和下一步…" rows={3}/><button className="action">保存跟进</button></form><h3>最近动态</h3><div className="timeline">{selected.activities?.map(a=><div key={a.id}><i/><p><b>{a.type} · {a.createdBy.displayName}</b><span>{a.content}</span><small>{new Date(a.occurredAt).toLocaleString('zh-CN')}</small></p></div>)}{!selected.activities?.length&&<p className="muted">尚无跟进记录</p>}</div></section></div>}
  </AppShell>
}
