'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AppShell } from './AppShell';
import { api, withQuery } from '@/lib/api';

type Lead={id:string;leadNo:string;name:string;contactName?:string;phone?:string;source?:string;status:string;intentSummary?:string;estimatedValue?:string;nextFollowUpAt?:string;owner:{displayName:string};orgUnit:{name:string};_count:{activities:number};activities?:{id:string;type:string;content:string;occurredAt:string;createdBy:{displayName:string}}[];convertedCustomerId?:string};
type Result={items:Lead[];total:number;summary:Record<string,number>};
const statuses:Record<string,string>={NEW:'新线索',CONTACTED:'已联系',QUALIFYING:'需求确认',WON:'已转客户',LOST:'已流失'};
export function CrmLeadsPage(){
  const [data,setData]=useState<Result>({items:[],total:0,summary:{}});const [keyword,setKeyword]=useState('');const [status,setStatus]=useState('');const [showCreate,setShowCreate]=useState(false);const [selected,setSelected]=useState<Lead|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api<Result>(withQuery('/crm/leads',{keyword,status})))}catch(e){setError(e instanceof Error?e.message:'读取失败')}finally{setLoading(false)}},[keyword,status]);useEffect(()=>{void load()},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form));const values={...raw,estimatedValue:raw.estimatedValue?Number(raw.estimatedValue):undefined,nextFollowUpAt:raw.nextFollowUpAt?new Date(String(raw.nextFollowUpAt)).toISOString():undefined};try{await api('/crm/leads',{method:'POST',body:JSON.stringify(values)});form.reset();setShowCreate(false);await load()}catch(err){setError(err instanceof Error?err.message:'新增失败')}}
  async function open(id:string){try{setSelected(await api<Lead>(`/crm/leads/${id}`))}catch(e){setError(e instanceof Error?e.message:'读取失败')}}
  async function setLeadStatus(value:string){if(!selected)return;try{await api(`/crm/leads/${selected.id}`,{method:'PATCH',body:JSON.stringify({status:value})});await open(selected.id);await load()}catch(e){setError(e instanceof Error?e.message:'更新失败')}}
  async function follow(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const form=e.currentTarget;try{await api(`/crm/leads/${selected.id}/activities`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await open(selected.id);await load()}catch(err){setError(err instanceof Error?err.message:'保存失败')}}
  async function convert(){if(!selected||!confirm('确认将此线索转为正式客户？'))return;try{const customer=await api<{customerNo:string}>(`/crm/leads/${selected.id}/convert`,{method:'POST'});alert(`已创建客户 ${customer.customerNo}`);setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'转化失败')}}
  const pipeline=['NEW','CONTACTED','QUALIFYING','WON'];
  return <AppShell title="线索管理" subtitle="从首次咨询到正式客户，保留完整转化轨迹。"><div className="pipeline">{pipeline.map((key,i)=><article key={key}><span>0{i+1}</span><div><small>{statuses[key]}</small><strong>{data.summary[key]??0}</strong></div></article>)}</div><div className="crm-toolbar"><div className="search-box"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索线索、联系人或电话"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部阶段</option>{Object.entries(statuses).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div><button className="action" onClick={()=>setShowCreate(true)}>＋ 新增线索</button></div>{error&&<div className="error block">{error}</div>}<div className="crm-table"><table><thead><tr><th>线索</th><th>联系人</th><th>意向金额</th><th>来源</th><th>负责人</th><th>下次跟进</th><th>阶段</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id} onClick={()=>void open(item.id)}><td><b>{item.name}</b><small>{item.leadNo}</small></td><td>{item.contactName??'—'}<small>{item.phone??'未留电话'}</small></td><td>{item.estimatedValue?`¥${Number(item.estimatedValue).toLocaleString()}`:'待评估'}</td><td>{item.source??'—'}</td><td>{item.owner.displayName}<small>{item._count.activities} 次跟进</small></td><td>{item.nextFollowUpAt?new Date(item.nextFollowUpAt).toLocaleDateString('zh-CN'):'未安排'}</td><td><span className={`state ${item.status.toLowerCase()}`}>{statuses[item.status]}</span></td></tr>)}</tbody></table>{loading&&<div className="empty">正在读取线索…</div>}{!loading&&!data.items.length&&<div className="empty">暂无符合条件的线索</div>}</div>
  {showCreate&&<div className="drawer-mask" onMouseDown={()=>setShowCreate(false)}><section className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowCreate(false)}>×</button><p className="eyebrow">NEW LEAD</p><h2>登记销售线索</h2><form className="crm-form" onSubmit={create}><label>项目/线索名称<input name="name" required placeholder="例如：杭州湖畔别墅全屋项目"/></label><div><label>联系人<input name="contactName"/></label><label>电话<input name="phone"/></label></div><label>来源<input name="source" placeholder="官网咨询、展会、转介绍等"/></label><label>预计金额<input name="estimatedValue" type="number" min="0" step="1000"/></label><label>下次跟进<input name="nextFollowUpAt" type="datetime-local"/></label><label>需求概述<textarea name="intentSummary" rows={4}/></label><button className="primary">保存销售线索</button></form></section></div>}
  {selected&&<div className="drawer-mask" onMouseDown={()=>setSelected(null)}><section className="drawer wide" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.leadNo}</p><h2>{selected.name}</h2><div className="detail-meta"><span>{selected.contactName??'未填写联系人'}</span><span>{selected.phone??'未留电话'}</span><span>{selected.owner.displayName}</span></div><p className="intent">{selected.intentSummary??'暂未记录需求概述'}</p><h3>推进阶段</h3><div className="stage-actions">{Object.entries(statuses).map(([key,label])=><button className={selected.status===key?'current':''} onClick={()=>void setLeadStatus(key)} key={key}>{label}</button>)}</div>{!selected.convertedCustomerId&&selected.status!=='LOST'&&<button className="convert" onClick={()=>void convert()}>转为正式客户 →</button>}<h3>新增跟进</h3><form className="follow-form" onSubmit={follow}><select name="type" defaultValue="CALL"><option value="CALL">电话</option><option value="MESSAGE">微信/消息</option><option value="VISIT">拜访</option><option value="MEETING">会议</option><option value="NOTE">备注</option></select><textarea name="content" required placeholder="记录本次沟通和下一步…" rows={3}/><button className="action">保存跟进</button></form><h3>跟进时间线</h3><div className="timeline">{selected.activities?.map(a=><div key={a.id}><i/><p><b>{a.type} · {a.createdBy.displayName}</b><span>{a.content}</span><small>{new Date(a.occurredAt).toLocaleString('zh-CN')}</small></p></div>)}{!selected.activities?.length&&<p className="muted">尚无跟进记录</p>}</div></section></div>}
  </AppShell>
}
