'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api, type Principal } from '@/lib/api';
import { AppShell } from './AppShell';

type Dashboard = { receivables: { count: number; total: number; paid: number; outstanding: number }; payables: { count: number; total: number; paid: number; outstanding: number }; operating: { orderValue: number; purchaseValue: number; expenseValue: number; payrollValue: number; estimatedContribution: number }; cash: { in: number; out: number; net: number }; recent: Array<{ id: string; no: string; direction: string; amount: number; party: string; sourceNo: string; occurredAt: string }> };
type Receipt = { id: string; receiptNo: string; amount: string; method: string; receivedAt: string; transactionRef?: string; collectedBy: { displayName: string } };
type Payment = { id: string; paymentNo: string; amount: string; method: string; paidAt: string; transactionRef?: string; paidBy: { displayName: string } };
type Receivable = { id: string; receivableNo: string; status: string; totalAmount: string; paidAmount: string; outstandingAmount: number; dueDate?: string; customer: { customerNo: string; name: string }; salesOrder: { orderNo: string; title: string; owner: { displayName: string } }; receipts: Receipt[] };
type Payable = { id: string; payableNo: string; status: string; totalAmount: string; paidAmount: string; outstandingAmount: number; dueDate?: string; supplier: { supplierNo: string; name: string }; purchaseOrder: { purchaseOrderNo: string; status: string; buyer: { displayName: string } }; payments: Payment[] };
type Expense = { id: string; expenseNo: string; category: string; description: string; amount: string; taxAmount: string; status: string; occurredAt: string; dueDate?: string; paidAt?: string; applicant: { displayName: string }; approvedBy?: { displayName: string } };
type Payroll = { id: string; payrollNo: string; period: string; baseAmount: string; bonusAmount: string; deductionAmount: string; netAmount: string; status: string; employee: { id: string; username: string; displayName: string } };
type Employee = { id: string; username: string; displayName: string };
type Paged<T> = { items: T[]; total: number };

const statusNames: Record<string, string> = { UNPAID: '未结清', PARTIALLY_PAID: '部分结清', PAID: '已结清', OVERDUE: '已逾期', VOID: '已作废', DRAFT: '草稿', SUBMITTED: '待审批', APPROVED: '已审批', REJECTED: '已驳回', CONFIRMED: '已确认' };
const methods: Record<string, string> = { BANK_TRANSFER: '银行转账', CASH: '现金', WECHAT: '微信', ALIPAY: '支付宝', CARD: '银行卡', OTHER: '其他' };
const money = (value: string | number = 0) => new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format(Number(value));
const emptyDashboard: Dashboard = { receivables: { count: 0, total: 0, paid: 0, outstanding: 0 }, payables: { count: 0, total: 0, paid: 0, outstanding: 0 }, operating: { orderValue: 0, purchaseValue: 0, expenseValue: 0, payrollValue: 0, estimatedContribution: 0 }, cash: { in: 0, out: 0, net: 0 }, recent: [] };

export function FinancePage() {
  const [dashboard, setDashboard] = useState<Dashboard>(emptyDashboard);
  const [receivables, setReceivables] = useState<Paged<Receivable>>({ items: [], total: 0 });
  const [payables, setPayables] = useState<Paged<Payable>>({ items: [], total: 0 });
  const [expenses, setExpenses] = useState<Paged<Expense>>({ items: [], total: 0 });
  const [payroll, setPayroll] = useState<Paged<Payroll>>({ items: [], total: 0 });
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [me, setMe] = useState<Principal | null>(null);
  const [tab, setTab] = useState<'receivables' | 'payables' | 'expenses' | 'payroll'>('receivables');
  const [keyword, setKeyword] = useState('');
  const [selected, setSelected] = useState<Receivable | Payable | null>(null);
  const [dialog, setDialog] = useState<'expense' | 'payroll' | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const q = `pageSize=100&keyword=${encodeURIComponent(keyword)}`;
      const [d, ar, ap, ex, py, people, principal] = await Promise.all([
        api<Dashboard>('/finance/dashboard'), api<Paged<Receivable>>(`/finance/receivables?${q}`).catch(() => ({ items: [], total: 0 })), api<Paged<Payable>>(`/finance/payables?${q}`).catch(() => ({ items: [], total: 0 })),
        api<Paged<Expense>>(`/finance/expenses?${q}`).catch(() => ({ items: [], total: 0 })), api<Paged<Payroll>>(`/finance/payroll?${q}`).catch(() => ({ items: [], total: 0 })), api<Employee[]>('/finance/employees').catch(() => []), api<Principal>('/me'),
      ]);
      setDashboard(d); setReceivables(ar); setPayables(ap); setExpenses(ex); setPayroll(py); setEmployees(people); setMe(principal);
    } catch (cause) { setError(cause instanceof Error ? cause.message : '读取财务数据失败'); }
    finally { setLoading(false); }
  }, [keyword]);
  useEffect(() => { void load(); }, [load]);

  const canCollect = me?.permissions.includes('finance.receivable.collect') ?? false;
  const canPay = me?.permissions.includes('finance.payable.pay') ?? false;
  const canCreateExpense = me?.permissions.includes('finance.expense.create') ?? false;
  const canApproveExpense = me?.permissions.includes('finance.expense.approve') ?? false;
  const canPayExpense = me?.permissions.includes('finance.expense.pay') ?? false;
  const canManagePayroll = me?.permissions.includes('finance.payroll.manage') ?? false;
  const canPayPayroll = me?.permissions.includes('finance.payroll.pay') ?? false;

  async function syncBills() { try { await Promise.all([canCollect ? api('/finance/receivables/sync', { method: 'POST' }) : null, canPay ? api('/finance/payables/sync', { method: 'POST' }) : null]); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '同步账单失败'); } }
  async function recordMoney(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!selected) return; const form = e.currentTarget, data = Object.fromEntries(new FormData(form)); const isReceivable = 'receivableNo' in selected;
    try { await api(`/finance/${isReceivable ? 'receivables' : 'payables'}/${selected.id}/${isReceivable ? 'receipts' : 'payments'}`, { method: 'POST', body: JSON.stringify({ amount: Number(data.amount), method: data.method, occurredAt: data.occurredAt ? new Date(String(data.occurredAt)).toISOString() : undefined, transactionRef: data.transactionRef || undefined, note: data.note || undefined }) }); setSelected(null); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : '登记收付失败'); }
  }
  async function createExpense(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget, data = Object.fromEntries(new FormData(form)); try { const result = await api<Expense>('/finance/expenses', { method: 'POST', body: JSON.stringify({ category: data.category, description: data.description, amount: Number(data.amount), taxAmount: Number(data.taxAmount || 0), occurredAt: new Date(String(data.occurredAt)).toISOString(), dueDate: data.dueDate ? new Date(String(data.dueDate)).toISOString() : undefined, notes: data.notes || undefined }) }); await api(`/finance/expenses/${result.id}/submit`, { method: 'POST' }); setDialog(null); form.reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '新增费用失败'); } }
  async function expenseAction(id: string, action: 'approve' | 'reject' | 'pay') { try { await api(`/finance/expenses/${id}/${action}`, { method: 'POST', body: action === 'pay' ? '{}' : undefined }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '费用操作失败'); } }
  async function createPayroll(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget, data = Object.fromEntries(new FormData(form)); try { const result = await api<Payroll>('/finance/payroll', { method: 'POST', body: JSON.stringify({ employeeId: data.employeeId, period: data.period, baseAmount: Number(data.baseAmount), bonusAmount: Number(data.bonusAmount || 0), deductionAmount: Number(data.deductionAmount || 0), notes: data.notes || undefined }) }); await api(`/finance/payroll/${result.id}/confirm`, { method: 'POST' }); setDialog(null); form.reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '新增工资单失败'); } }
  async function payrollAction(id: string, action: 'confirm' | 'pay') { try { await api(`/finance/payroll/${id}/${action}`, { method: 'POST', body: action === 'pay' ? '{}' : undefined }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '工资操作失败'); } }

  return <AppShell title="财务经营核算中心" subtitle="销售应收、采购应付、费用和工资统一形成可追溯凭证，并实时回写业务单据的结算状态。">
    <div className="finance-kpis"><article><span>应收余额</span><strong>{money(dashboard.receivables.outstanding)}</strong><small>{dashboard.receivables.count} 张应收单</small></article><article><span>应付余额</span><strong>{money(dashboard.payables.outstanding)}</strong><small>{dashboard.payables.count} 张应付单</small></article><article><span>现金净流入</span><strong className={dashboard.cash.net < 0 ? 'negative' : ''}>{money(dashboard.cash.net)}</strong><small>流入 {money(dashboard.cash.in)} · 流出 {money(dashboard.cash.out)}</small></article><article><span>经营贡献估算</span><strong className={dashboard.operating.estimatedContribution < 0 ? 'negative' : ''}>{money(dashboard.operating.estimatedContribution)}</strong><small>订单额减采购、费用与工资</small></article></div>
    <div className="profit-bridge"><div><small>订单价值</small><b>{money(dashboard.operating.orderValue)}</b></div><i>−</i><div><small>采购承诺</small><b>{money(dashboard.operating.purchaseValue)}</b></div><i>−</i><div><small>审批费用</small><b>{money(dashboard.operating.expenseValue)}</b></div><i>−</i><div><small>确认工资</small><b>{money(dashboard.operating.payrollValue)}</b></div><i>＝</i><div className="result"><small>贡献估算</small><b>{money(dashboard.operating.estimatedContribution)}</b></div></div>
    <div className="crm-toolbar"><div className="finance-tabs">{(['receivables', 'payables', 'expenses', 'payroll'] as const).map((value) => <button className={tab === value ? 'active' : ''} onClick={() => setTab(value)} key={value}>{value === 'receivables' ? '应收收款' : value === 'payables' ? '应付付款' : value === 'expenses' ? '费用管理' : '工资管理'}</button>)}</div><div className="toolbar-actions"><input className="finance-search" value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="搜索单号或往来单位"/>{(canCollect || canPay) && <button className="secondary-action" onClick={() => void syncBills()}>同步业务账单</button>}{tab === 'expenses' && canCreateExpense && <button className="action" onClick={() => setDialog('expense')}>＋ 费用申请</button>}{tab === 'payroll' && canManagePayroll && <button className="action" onClick={() => setDialog('payroll')}>＋ 工资单</button>}</div></div>
    {error && <div className="error block">{error}</div>}
    {tab === 'receivables' && <FinanceTable headers={['应收单 / 订单', '客户', '应收金额', '已收金额', '到期日', '状态']} rows={receivables.items.map((item) => <tr key={item.id} onClick={() => setSelected(item)}><td><b>{item.receivableNo}</b><small>{item.salesOrder.orderNo} · {item.salesOrder.owner.displayName}</small></td><td><b>{item.customer.name}</b><small>{item.customer.customerNo}</small></td><td><b>{money(item.totalAmount)}</b></td><td><strong className="finance-in">{money(item.paidAmount)}</strong><small>待收 {money(item.outstandingAmount)}</small></td><td>{item.dueDate ? new Date(item.dueDate).toLocaleDateString('zh-CN') : '未设置'}</td><td><span className={`state ${item.status.toLowerCase()}`}>{statusNames[item.status]}</span></td></tr>)} loading={loading}/>} 
    {tab === 'payables' && <FinanceTable headers={['应付单 / 采购单', '供应商', '应付金额', '已付金额', '到期日', '状态']} rows={payables.items.map((item) => <tr key={item.id} onClick={() => setSelected(item)}><td><b>{item.payableNo}</b><small>{item.purchaseOrder.purchaseOrderNo} · {item.purchaseOrder.buyer.displayName}</small></td><td><b>{item.supplier.name}</b><small>{item.supplier.supplierNo}</small></td><td><b>{money(item.totalAmount)}</b></td><td><strong className="finance-out">{money(item.paidAmount)}</strong><small>待付 {money(item.outstandingAmount)}</small></td><td>{item.dueDate ? new Date(item.dueDate).toLocaleDateString('zh-CN') : '未设置'}</td><td><span className={`state ${item.status.toLowerCase()}`}>{statusNames[item.status]}</span></td></tr>)} loading={loading}/>} 
    {tab === 'expenses' && <FinanceTable headers={['费用单', '类别 / 说明', '申请人', '金额', '发生日期', '状态 / 操作']} rows={expenses.items.map((item) => <tr key={item.id}><td><b>{item.expenseNo}</b><small>税额 {money(item.taxAmount)}</small></td><td><b>{item.category}</b><small>{item.description}</small></td><td>{item.applicant.displayName}</td><td><b>{money(item.amount)}</b></td><td>{new Date(item.occurredAt).toLocaleDateString('zh-CN')}</td><td><span className={`state ${item.status.toLowerCase()}`}>{statusNames[item.status]}</span><div className="inline-actions">{item.status === 'SUBMITTED' && canApproveExpense && <><button onClick={() => void expenseAction(item.id, 'approve')}>通过</button><button className="danger" onClick={() => void expenseAction(item.id, 'reject')}>驳回</button></>}{item.status === 'APPROVED' && canPayExpense && <button onClick={() => void expenseAction(item.id, 'pay')}>支付</button>}</div></td></tr>)} loading={loading}/>} 
    {tab === 'payroll' && <FinanceTable headers={['工资单', '员工', '基本 / 奖金 / 扣款', '实发金额', '期间', '状态 / 操作']} rows={payroll.items.map((item) => <tr key={item.id}><td><b>{item.payrollNo}</b></td><td><b>{item.employee.displayName}</b><small>{item.employee.username}</small></td><td><small>{money(item.baseAmount)} ＋ {money(item.bonusAmount)} − {money(item.deductionAmount)}</small></td><td><b>{money(item.netAmount)}</b></td><td>{item.period}</td><td><span className={`state ${item.status.toLowerCase()}`}>{statusNames[item.status]}</span><div className="inline-actions">{item.status === 'DRAFT' && canManagePayroll && <button onClick={() => void payrollAction(item.id, 'confirm')}>确认</button>}{item.status === 'CONFIRMED' && canPayPayroll && <button onClick={() => void payrollAction(item.id, 'pay')}>发放</button>}</div></td></tr>)} loading={loading}/>} 
    {selected && <FinanceDialog close={() => setSelected(null)} eyebrow={'receivableNo' in selected ? selected.receivableNo : selected.payableNo} title={'receivableNo' in selected ? selected.customer.name : selected.supplier.name}><div className="stock-focus"><article><small>总金额</small><b>{money(selected.totalAmount)}</b></article><article><small>已结算</small><b>{money(selected.paidAmount)}</b></article><article><small>未结算</small><b>{money(selected.outstandingAmount)}</b></article></div><div className="finance-history">{('receipts' in selected ? selected.receipts : selected.payments).map((entry) => <article key={entry.id}><div><b>{'receiptNo' in entry ? entry.receiptNo : entry.paymentNo}</b><small>{methods[entry.method]} · {new Date('receivedAt' in entry ? entry.receivedAt : entry.paidAt).toLocaleString('zh-CN')}</small></div><strong>{money(entry.amount)}</strong></article>)}</div>{selected.outstandingAmount > 0 && (('receivableNo' in selected && canCollect) || ('payableNo' in selected && canPay)) && <form className="crm-form" onSubmit={recordMoney}><div><label>{'receivableNo' in selected ? '本次收款' : '本次付款'}<input name="amount" type="number" step="0.01" min="0.01" max={selected.outstandingAmount} required/></label><label>支付方式<select name="method" defaultValue="BANK_TRANSFER">{Object.entries(methods).map(([value, name]) => <option value={value} key={value}>{name}</option>)}</select></label></div><div><label>发生日期<input name="occurredAt" type="date"/></label><label>交易参考号<input name="transactionRef"/></label></div><label>备注<textarea name="note" rows={2}/></label><button className="primary">确认登记</button></form>}</FinanceDialog>}
    {dialog === 'expense' && <FinanceDialog close={() => setDialog(null)} eyebrow="EXPENSE APPLICATION" title="新建费用申请"><form className="crm-form" onSubmit={createExpense}><div><label>费用类别<input name="category" required placeholder="运输费、厂房费…"/></label><label>发生日期<input name="occurredAt" type="date" required/></label></div><label>费用说明<input name="description" required/></label><div><label>含税金额<input name="amount" type="number" step="0.01" min="0.01" required/></label><label>其中税额<input name="taxAmount" type="number" step="0.01" min="0"/></label></div><label>计划付款日<input name="dueDate" type="date"/></label><label>备注<textarea name="notes" rows={3}/></label><button className="primary">保存并提交审批</button></form></FinanceDialog>}
    {dialog === 'payroll' && <FinanceDialog close={() => setDialog(null)} eyebrow="PAYROLL" title="创建月度工资单"><form className="crm-form" onSubmit={createPayroll}><label>员工<select name="employeeId" defaultValue="" required><option value="" disabled>请选择员工</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.displayName} · {employee.username}</option>)}</select></label><label>工资期间<input name="period" type="month" required/></label><div><label>基本工资<input name="baseAmount" type="number" step="0.01" min="0" required/></label><label>奖金<input name="bonusAmount" type="number" step="0.01" min="0"/></label></div><label>扣款<input name="deductionAmount" type="number" step="0.01" min="0"/></label><label>备注<textarea name="notes" rows={3}/></label><button className="primary">保存并确认</button></form></FinanceDialog>}
  </AppShell>;
}

function FinanceTable({ headers, rows, loading }: { headers: string[]; rows: React.ReactNode[]; loading: boolean }) { return <div className="crm-table finance-table"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows}</tbody></table>{loading && <div className="empty">正在读取财务数据…</div>}{!loading && rows.length === 0 && <div className="empty">暂无符合条件的数据</div>}</div>; }
function FinanceDialog({ close, eyebrow, title, children }: { close: () => void; eyebrow: string; title: string; children: React.ReactNode }) { return <div className="drawer-mask" onMouseDown={close}><section className="drawer finance-drawer" onMouseDown={(event) => event.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section></div>; }
