'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api, type Principal } from '@/lib/api';
import { AppShell } from './AppShell';

type Channel = { id: string; type: string; name: string; status: string; config?: Record<string, unknown>; lastSyncedAt?: string; lastError?: string; _count: { apiClients: number; subscriptions: number } };
type Client = { id: string; name: string; clientKey: string; scopes: string[]; active: boolean; lastUsedAt?: string; channel?: { name: string } };
type Webhook = { id: string; name: string; url: string; eventTypes: string[]; active: boolean; channel?: { id: string; name: string }; _count: { deliveries: number } };
type Outbox = { id: string; eventId: string; eventType: string; aggregateType: string; aggregateId: string; createdAt: string; deliveries: Array<{ id: string; status: string; attempts: number; responseStatus?: number; lastError?: string; subscription: { name: string; url: string } }> };
type SecretResult = { kind: 'client' | 'webhook'; name: string; key?: string; secret: string; warning: string };
const names: Record<string, string> = { WEBSITE: '官网', WECHAT_MINI_PROGRAM: '微信小程序', TAOBAO: '淘宝', WECOM: '企业微信', DESIGNER_PORTAL: '设计师中心', DEALER_PORTAL: '经销商中心' };

export function IntegrationsPage() {
  const [channels, setChannels] = useState<Channel[]>([]); const [clients, setClients] = useState<Client[]>([]); const [webhooks, setWebhooks] = useState<Webhook[]>([]); const [outbox, setOutbox] = useState<{ items: Outbox[]; total: number }>({ items: [], total: 0 }); const [me, setMe] = useState<Principal | null>(null); const [tab, setTab] = useState<'channels' | 'clients' | 'webhooks'>('channels'); const [dialog, setDialog] = useState<'channel' | 'client' | 'webhook' | 'event' | null>(null); const [editingChannel, setEditingChannel] = useState<Channel | null>(null); const [secret, setSecret] = useState<SecretResult | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [c, a, w, o, u] = await Promise.all([api<Channel[]>('/integrations/channels'), api<Client[]>('/integrations/clients'), api<Webhook[]>('/integrations/webhooks'), api<{ items: Outbox[]; total: number }>('/integrations/outbox?pageSize=50'), api<Principal>('/me')]); setChannels(c); setClients(a); setWebhooks(w); setOutbox(o); setMe(u); } catch (e) { setError(e instanceof Error ? e.message : '读取集成配置失败'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const canManage = me?.permissions.includes('integration.manage') ?? false, canClient = me?.permissions.includes('integration.client.manage') ?? false, canWebhook = me?.permissions.includes('integration.webhook.manage') ?? false, canDispatch = me?.permissions.includes('integration.webhook.dispatch') ?? false;
  async function toggleChannel(item: Channel) { try { await api(`/integrations/channels/${item.type}`, { method: 'PATCH', body: JSON.stringify({ name: item.name, status: item.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE', config: item.config ?? {} }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '更新渠道失败'); } }
  async function configureChannel(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editingChannel) return; const form = event.currentTarget, data = Object.fromEntries(new FormData(form)); const adapterUrl = String(data.adapterUrl), config = { ...(editingChannel.config ?? {}), adapterUrl, credentialRef: data.credentialRef, accountId: data.accountId || undefined }; try { await api(`/integrations/channels/${editingChannel.type}`, { method: 'PATCH', body: JSON.stringify({ name: data.name, status: editingChannel.status, config }) }); const adapters = webhooks.filter((item) => item.channel?.id === editingChannel.id && item.eventTypes.includes('catalog.product.sync.requested')); let createdSecret:SecretResult|null=null; if (!adapters.some((item) => item.active && item.url === adapterUrl)) { for (const old of adapters.filter((item) => item.active)) await api(`/integrations/webhooks/${old.id}`, { method: 'PATCH', body: JSON.stringify({ active: false }) }); const result = await api<{name:string;signingSecret:string;warning:string}>('/integrations/webhooks', { method: 'POST', body: JSON.stringify({ name: `${String(data.name)}商品同步适配器`, url: adapterUrl, channelId: editingChannel.id, eventTypes: ['catalog.product.sync.requested'] }) }); createdSecret={kind:'webhook',name:result.name,secret:result.signingSecret,warning:result.warning}; } setDialog(null); setEditingChannel(null); if(createdSecret)setSecret(createdSecret); await load(); } catch (e) { setError(e instanceof Error ? e.message : '保存渠道配置失败'); } }
  async function createClient(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget, data = Object.fromEntries(new FormData(form)); try { const result = await api<{ name: string; clientKey: string; clientSecret: string; warning: string }>('/integrations/clients', { method: 'POST', body: JSON.stringify({ name: data.name, channelId: data.channelId || undefined, scopes: form.querySelectorAll<HTMLInputElement>('input[name="scopes"]:checked').length ? Array.from(form.querySelectorAll<HTMLInputElement>('input[name="scopes"]:checked')).map((x) => x.value) : [] }) }); setDialog(null); setSecret({ kind: 'client', name: result.name, key: result.clientKey, secret: result.clientSecret, warning: result.warning }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '创建 API 客户端失败'); } }
  async function createWebhook(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget, data = Object.fromEntries(new FormData(form)); try { const result = await api<{ name: string; signingSecret: string; warning: string }>('/integrations/webhooks', { method: 'POST', body: JSON.stringify({ name: data.name, url: data.url, channelId: data.channelId || undefined, eventTypes: String(data.eventTypes).split(',').map((x) => x.trim()).filter(Boolean) }) }); setDialog(null); setSecret({ kind: 'webhook', name: result.name, secret: result.signingSecret, warning: result.warning }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '创建 Webhook 失败'); } }
  async function enqueue(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget, data = Object.fromEntries(new FormData(form)); try { await api('/integrations/events', { method: 'POST', body: JSON.stringify({ eventType: data.eventType, aggregateType: data.aggregateType, aggregateId: data.aggregateId, payload: { message: data.message, emittedFrom: 'management-console' } }) }); setDialog(null); await load(); setTab('webhooks'); } catch (e) { setError(e instanceof Error ? e.message : '创建事件失败'); } }
  async function dispatch() { try { await api('/integrations/dispatch', { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '投递失败'); } }
  return <AppShell title="多端集成中心" subtitle="官网、小程序、淘宝、企业微信、设计师与经销商门户共享统一 REST 凭据和可重试 Webhook 出站箱。"><div className="integration-summary"><article><b>6</b><span>预置渠道</span></article><article><b>{channels.filter((x) => x.status === 'ACTIVE').length}</b><span>已启用</span></article><article><b>{clients.filter((x) => x.active).length}</b><span>API 客户端</span></article><article><b>{outbox.total}</b><span>出站事件</span></article></div><div className="crm-toolbar"><div className="finance-tabs"><button className={tab === 'channels' ? 'active' : ''} onClick={() => setTab('channels')}>渠道</button><button className={tab === 'clients' ? 'active' : ''} onClick={() => setTab('clients')}>REST 客户端</button><button className={tab === 'webhooks' ? 'active' : ''} onClick={() => setTab('webhooks')}>Webhook</button></div><div className="toolbar-actions">{tab === 'clients' && canClient && <button className="action" onClick={() => setDialog('client')}>＋ API 客户端</button>}{tab === 'webhooks' && canWebhook && <><button onClick={() => setDialog('webhook')}>＋ 订阅端点</button><button onClick={() => setDialog('event')}>创建测试事件</button></>}{tab === 'webhooks' && canDispatch && <button className="action" onClick={() => void dispatch()}>投递待发事件</button>}</div></div>{error && <div className="error block">{error}</div>}
    {tab === 'channels' && <div className="channel-grid">{channels.map((item) => <article key={item.id}><div className="channel-mark">{names[item.type]?.slice(0, 2)}</div><div><span className={`mini ${item.status === 'ACTIVE' ? 'ready' : 'reserved'}`}>{item.status === 'ACTIVE' ? '已启用' : '未启用'}</span><h3>{item.name}</h3><p>{item._count.apiClients} 个客户端 · {item._count.subscriptions} 个订阅{typeof item.config?.adapterUrl === 'string' ? ' · 已配置适配器' : ''}</p></div>{canManage && <div className="inline-actions"><button onClick={() => { setEditingChannel(item); setDialog('channel'); }}>配置</button><button onClick={() => void toggleChannel(item)}>{item.status === 'ACTIVE' ? '停用' : '启用'}</button></div>}</article>)}</div>}
    {tab === 'clients' && <div className="crm-table"><table><thead><tr><th>客户端</th><th>渠道</th><th>Client Key</th><th>权限范围</th><th>最后使用</th><th>状态</th></tr></thead><tbody>{clients.map((item) => <tr key={item.id}><td><b>{item.name}</b></td><td>{item.channel?.name ?? '通用'}</td><td><code>{item.clientKey}</code></td><td>{item.scopes.join(' · ')}</td><td>{item.lastUsedAt ? new Date(item.lastUsedAt).toLocaleString('zh-CN') : '从未'}</td><td><span className={`state ${item.active ? 'active' : 'cancelled'}`}>{item.active ? '有效' : '停用'}</span></td></tr>)}</tbody></table></div>}
    {tab === 'webhooks' && <><div className="webhook-strip">{webhooks.map((item) => <article key={item.id}><b>{item.name}</b><span>{item.url}</span><small>{item.eventTypes.join(' · ')} · {item._count.deliveries} 次投递</small></article>)}</div><div className="section-title"><div><h3>出站箱</h3><p>每个事件按订阅端点独立重试，避免单端故障阻塞其他渠道。</p></div></div><div className="outbox-list">{outbox.items.map((item) => <article key={item.id}><div><b>{item.eventType}</b><small>{item.aggregateType} · {item.aggregateId}</small></div><span>{item.eventId.slice(0, 8)}</span><div>{item.deliveries.length ? item.deliveries.map((d) => <em className={`delivery-${d.status.toLowerCase()}`} key={d.id}>{d.subscription.name}: {d.status} ({d.attempts})</em>) : <em>无匹配订阅</em>}</div></article>)}</div></>}
    {loading && <div className="empty">正在读取多端集成状态…</div>}
    {dialog === 'channel' && editingChannel && <Dialog close={() => { setDialog(null); setEditingChannel(null); }} title={`配置${names[editingChannel.type]??editingChannel.name}`}><form className="crm-form" onSubmit={configureChannel}><label>渠道名称<input name="name" required defaultValue={editingChannel.name}/></label><label>渠道适配器 URL<input name="adapterUrl" type="url" required defaultValue={String(editingChannel.config?.adapterUrl??'')} placeholder="https://adapter.example.com/ffai/product-sync"/><small>由适配器接收标准商品载荷，再调用淘宝或微信官方开放接口。</small></label><label>凭据引用<input name="credentialRef" required defaultValue={String(editingChannel.config?.credentialRef??'')} placeholder="例如：secret://taobao/main-shop"/><small>这里只保存密钥管理系统中的引用，不直接保存平台密钥。</small></label><label>店铺 / App ID<input name="accountId" defaultValue={String(editingChannel.config?.accountId??'')}/></label><button className="primary">保存渠道配置</button></form></Dialog>}
    {dialog === 'client' && <Dialog close={() => setDialog(null)} title="创建 REST API 客户端"><form className="crm-form" onSubmit={createClient}><label>客户端名称<input name="name" required /></label><label>关联渠道<select name="channelId" defaultValue=""><option value="">通用客户端</option>{channels.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label><fieldset className="scope-picker"><legend>授权 Scope</legend>{['catalog.read', 'order.status.read', 'events.write'].map((x) => <label key={x}><input type="checkbox" name="scopes" value={x} />{x}</label>)}</fieldset><button className="primary">生成凭据</button></form></Dialog>}
    {dialog === 'webhook' && <Dialog close={() => setDialog(null)} title="新增 Webhook 订阅"><form className="crm-form" onSubmit={createWebhook}><label>订阅名称<input name="name" required /></label><label>关联渠道<select name="channelId" defaultValue=""><option value="">通用订阅</option>{channels.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>接收 URL<input name="url" type="url" required placeholder="https://example.com/webhooks/ffai" /></label><label>事件类型<input name="eventTypes" required defaultValue="order.status.changed" /><small>多个事件用逗号分隔</small></label><button className="primary">创建订阅</button></form></Dialog>}
    {dialog === 'event' && <Dialog close={() => setDialog(null)} title="创建出站测试事件"><form className="crm-form" onSubmit={enqueue}><label>事件类型<input name="eventType" required defaultValue="order.status.changed" /></label><div><label>聚合类型<input name="aggregateType" required defaultValue="SALES_ORDER" /></label><label>聚合 ID<input name="aggregateId" required /></label></div><label>消息<input name="message" required /></label><button className="primary">写入出站箱</button></form></Dialog>}
    {secret && <Dialog close={() => setSecret(null)} title="请立即保存密钥"><div className="secret-box"><b>{secret.name}</b>{secret.key && <label>Client Key<code>{secret.key}</code></label>}<label>{secret.kind === 'client' ? 'Client Secret' : 'Signing Secret'}<code>{secret.secret}</code></label><p>{secret.warning}</p></div><button className="primary" onClick={() => setSecret(null)}>我已安全保存</button></Dialog>}
  </AppShell>;
}
function Dialog({ close, title, children }: { close: () => void; title: string; children: React.ReactNode }) { return <div className="drawer-mask" onMouseDown={close}><section className="drawer integration-drawer" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">INTEGRATION</p><h2>{title}</h2>{children}</section></div>; }
