'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AppShell } from './AppShell';
import { api, withQuery } from '@/lib/api';

type Project={id:string;projectNo:string;name:string;status:string;address?:string;estimatedBudget?:string;expectedDeliveryAt?:string;notes?:string;tags:string[];customer:{id:string;customerNo:string;name:string;phone?:string};owner:{displayName:string};orgUnit:{name:string};_count:{spaces:number;members:number;designVersions:number};spaces?:Space[];members?:Member[];designVersions?:Design[]};
type Space={id:string;name:string;roomType?:string;floor?:string;lengthMm?:number;widthMm?:number;heightMm?:number;areaSqm?:string;notes?:string};
type Member={userId:string;role:string;user:{displayName:string;username:string}};
type Design={id:string;versionNo:number;title:string;status:string;description?:string;reviewNote?:string;createdAt:string;createdBy:{displayName:string}};
type Customer={id:string;customerNo:string;name:string};
type Result={items:Project[];total:number;summary:Record<string,number>};
const statuses:Record<string,string>={INQUIRY:'需求沟通',MEASURING:'测量中',DESIGNING:'设计中',QUOTING:'报价中',CUSTOMER_REVIEW:'客户确认',CONFIRMED:'已确认',ON_HOLD:'暂缓',COMPLETED:'已完成',CANCELLED:'已取消'};
const designStatuses:Record<string,string>={DRAFT:'草稿',INTERNAL_REVIEW:'内部评审',CUSTOMER_REVIEW:'客户评审',APPROVED:'已通过',REJECTED:'已退回'};

export function ProjectsPage(){
  const [data,setData]=useState<Result>({items:[],total:0,summary:{}});const [customers,setCustomers]=useState<Customer[]>([]);const [keyword,setKeyword]=useState('');const [status,setStatus]=useState('');const [selected,setSelected]=useState<Project|null>(null);const [showCreate,setShowCreate]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [projects,customerData]=await Promise.all([api<Result>(withQuery('/projects',{keyword,status})),api<{items:Customer[]}>('/crm/customers?pageSize=100')]);setData(projects);setCustomers(customerData.items)}catch(e){setError(e instanceof Error?e.message:'读取失败')}finally{setLoading(false)}},[keyword,status]);
  useEffect(()=>{void load()},[load]);
  async function open(id:string){try{setSelected(await api<Project>(`/projects/${id}`))}catch(e){setError(e instanceof Error?e.message:'读取项目失败')}}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form));const values={...raw,estimatedBudget:raw.estimatedBudget?Number(raw.estimatedBudget):undefined,expectedDeliveryAt:raw.expectedDeliveryAt?new Date(String(raw.expectedDeliveryAt)).toISOString():undefined};try{await api('/projects',{method:'POST',body:JSON.stringify(values)});form.reset();setShowCreate(false);await load()}catch(err){setError(err instanceof Error?err.message:'创建失败')}}
  async function changeStatus(next:string){if(!selected)return;try{await api(`/projects/${selected.id}`,{method:'PATCH',body:JSON.stringify({status:next})});await open(selected.id);await load()}catch(e){setError(e instanceof Error?e.message:'更新失败')}}
  async function addSpace(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form));const numeric=['lengthMm','widthMm','heightMm','areaSqm'];const values:Record<string,unknown>={...raw};numeric.forEach(key=>{values[key]=raw[key]?Number(raw[key]):undefined});try{await api(`/projects/${selected.id}/spaces`,{method:'POST',body:JSON.stringify(values)});form.reset();await open(selected.id);await load()}catch(err){setError(err instanceof Error?err.message:'空间保存失败')}}
  async function addDesign(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const form=e.currentTarget;try{await api(`/projects/${selected.id}/design-versions`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await open(selected.id);await load()}catch(err){setError(err instanceof Error?err.message:'设计版本保存失败')}}
  async function review(versionId:string,next:string){if(!selected)return;try{await api(`/projects/${selected.id}/design-versions/${versionId}`,{method:'PATCH',body:JSON.stringify({status:next})});await open(selected.id)}catch(e){setError(e instanceof Error?e.message:'评审状态更新失败')}}
  const active=(data.summary.MEASURING??0)+(data.summary.DESIGNING??0)+(data.summary.QUOTING??0)+(data.summary.CUSTOMER_REVIEW??0);
  return <AppShell title="项目设计中心" subtitle="从客户需求、空间测量到设计版本确认，形成统一项目档案。"><div className="crm-stats"><article><span>项目总数</span><strong>{data.total}</strong></article><article><span>推进中</span><strong>{active}</strong></article><article><span>设计中</span><strong>{data.summary.DESIGNING??0}</strong></article><article><span>待客户确认</span><strong>{data.summary.CUSTOMER_REVIEW??0}</strong></article></div><div className="crm-toolbar"><div className="search-box"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索项目编号、名称或客户"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部阶段</option>{Object.entries(statuses).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div><button className="action" onClick={()=>setShowCreate(true)}>＋ 新建项目</button></div>{error&&<div className="error block">{error}</div>}<div className="project-grid">{data.items.map(project=><article key={project.id} onClick={()=>void open(project.id)}><div className="project-top"><span>{project.projectNo}</span><em className={`state ${project.status.toLowerCase()}`}>{statuses[project.status]}</em></div><h3>{project.name}</h3><p>{project.customer.name}</p><div className="project-progress"><i style={{width:`${Math.min(100,(Object.keys(statuses).indexOf(project.status)+1)*13)}%`}}/></div><div className="project-counts"><span><b>{project._count.spaces}</b>空间</span><span><b>{project._count.designVersions}</b>版本</span><span><b>{project._count.members}</b>成员</span></div><footer><span>{project.owner.displayName}</span><span>{project.expectedDeliveryAt?`预计 ${new Date(project.expectedDeliveryAt).toLocaleDateString('zh-CN')}`:'未设交期'}</span></footer></article>)}</div>{loading&&<div className="empty">正在读取项目…</div>}{!loading&&!data.items.length&&<div className="empty">暂无符合条件的项目</div>}
  {showCreate&&<div className="drawer-mask" onMouseDown={()=>setShowCreate(false)}><section className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowCreate(false)}>×</button><p className="eyebrow">NEW PROJECT</p><h2>建立项目档案</h2><form className="crm-form" onSubmit={create}><label>关联客户<select name="customerId" required defaultValue=""><option value="" disabled>请选择客户</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name} · {c.customerNo}</option>)}</select></label><label>项目名称<input name="name" required placeholder="例如：浦东顶层住宅全屋定制"/></label><label>项目地址<input name="address"/></label><div><label>预计预算<input name="estimatedBudget" type="number" min="0" step="1000"/></label><label>预计交付<input name="expectedDeliveryAt" type="date"/></label></div><label>项目说明<textarea name="notes" rows={4}/></label><button className="primary">保存并进入项目</button></form></section></div>}
  {selected&&<div className="drawer-mask" onMouseDown={()=>setSelected(null)}><section className="drawer project-drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.projectNo}</p><h2>{selected.name}</h2><div className="detail-meta"><span>{selected.customer.name}</span><span>{selected.owner.displayName} · {selected.orgUnit.name}</span><span>{selected.address??'未填写地址'}</span></div><h3>项目阶段</h3><div className="stage-actions project-stages">{Object.entries(statuses).map(([key,label])=><button className={selected.status===key?'current':''} key={key} onClick={()=>void changeStatus(key)}>{label}</button>)}</div><div className="project-columns"><div><h3>空间清单</h3><div className="space-list">{selected.spaces?.map(space=><article key={space.id}><b>{space.name}</b><span>{space.roomType??'未分类'} · {space.floor??'楼层未填'}</span><small>{space.lengthMm&&space.widthMm?`${space.lengthMm} × ${space.widthMm} × ${space.heightMm??'—'} mm`:space.areaSqm?`${space.areaSqm} ㎡`:'尺寸待测'}</small></article>)}</div><form className="compact-form" onSubmit={addSpace}><input name="name" required placeholder="空间名称"/><input name="roomType" placeholder="类型，如主卧"/><input name="areaSqm" type="number" step="0.01" placeholder="面积 ㎡"/><button className="action">添加空间</button></form></div><div><h3>项目成员</h3><div className="member-list">{selected.members?.map(member=><span key={member.userId}><i>{member.user.displayName.slice(0,1)}</i><b>{member.user.displayName}<small>{member.role}</small></b></span>)}</div></div></div><h3>设计版本</h3><div className="design-list">{selected.designVersions?.map(version=><article key={version.id}><div><b>V{version.versionNo} · {version.title}</b><span>{version.description??'无版本说明'}</span><small>{version.createdBy.displayName} · {new Date(version.createdAt).toLocaleString('zh-CN')}</small></div><div><em className={`state ${version.status.toLowerCase()}`}>{designStatuses[version.status]}</em><select value={version.status} onChange={e=>void review(version.id,e.target.value)}>{Object.entries(designStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div></article>)}</div><form className="compact-form design-form" onSubmit={addDesign}><input name="title" required placeholder="新版本标题"/><input name="description" placeholder="版本说明"/><button className="action">创建下一版本</button></form></section></div>}
  </AppShell>
}
