'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api, type Principal } from '@/lib/api';
import { AppShell } from './AppShell';

type Permission={id:string;code:string;name:string;resource:string;action:string}; type Menu={id:string;code:string;name:string;path?:string;type:string}; type Unit={id:string;name:string;path:string};
type Role={id:string;code:string;name:string;description?:string;active:boolean;isSystem:boolean;dataScope:string;_count:{users:number;permissions?:number};fieldPermissions?:Field[]};
type Field={resource:string;field:string;canRead:boolean;canWrite:boolean}; type FieldCatalog={resource:string;field:string;label:string};
type Detail=Role&{permissions:{permission:Permission}[];menus:{menu:Menu}[];customScopeUnits:{orgUnit:Unit}[];fieldPermissions:Field[]};
type Options={permissions:Permission[];menus:Menu[];orgUnits:Unit[];fieldCatalog:FieldCatalog[]};
type RoleForm={name:string;description:string;active:boolean;dataScope:string;permissionIds:string[];menuIds:string[];customOrgUnitIds:string[];fieldPermissions:Field[]};
const scopes:Record<string,string>={ALL:'全部数据',COMPANY:'本企业',DEPARTMENT:'本部门',DEPARTMENT_AND_CHILDREN:'本部门及下级',SELF:'仅本人',CUSTOM:'指定组织'};
const empty:RoleForm={name:'',description:'',active:true,dataScope:'SELF',permissionIds:[],menuIds:[],customOrgUnitIds:[],fieldPermissions:[]};

export function RolesPage(){
 const [me,setMe]=useState<Principal>(); const [roles,setRoles]=useState<Role[]>([]); const [options,setOptions]=useState<Options>({permissions:[],menus:[],orgUnits:[],fieldCatalog:[]}); const [selected,setSelected]=useState<Detail>(); const [form,setForm]=useState<RoleForm>(empty); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [creating,setCreating]=useState(false); const [newRole,setNewRole]=useState({code:'',name:'',description:'',dataScope:'SELF'});
 const canManage=me?.roleCodes.includes('OWNER')||me?.permissions.includes('system.role.manage');
 async function load(){try{const [principal,list,opts]=await Promise.all([api<Principal>('/me'),api<Role[]>('/system/roles'),api<Options>('/system/access-options')]);setMe(principal);setRoles(list);setOptions(opts)}catch(e){setError(e instanceof Error?e.message:'读取角色失败')}}
 useEffect(()=>{void load()},[]);
 const permissionGroups=useMemo(()=>Object.entries(options.permissions.reduce<Record<string,Permission[]>>((all,p)=>{(all[p.resource]??=[]).push(p);return all},{})),[options.permissions]);
 async function open(role:Role){setError('');setNotice('');setCreating(false);try{const detail=await api<Detail>(`/system/roles/${role.id}`);setSelected(detail);setForm({name:detail.name,description:detail.description??'',active:detail.active,dataScope:detail.dataScope,permissionIds:detail.permissions.map(x=>x.permission.id),menuIds:detail.menus.map(x=>x.menu.id),customOrgUnitIds:detail.customScopeUnits.map(x=>x.orgUnit.id),fieldPermissions:options.fieldCatalog.map(c=>detail.fieldPermissions.find(f=>f.resource===c.resource&&f.field===c.field)??{resource:c.resource,field:c.field,canRead:true,canWrite:true})})}catch(e){setError(e instanceof Error?e.message:'读取角色失败')}}
 function close(){setSelected(undefined);setCreating(false);setError('');setNotice('')}
 function toggle(key:'permissionIds'|'menuIds'|'customOrgUnitIds',id:string){setForm(x=>({...x,[key]:x[key].includes(id)?x[key].filter(v=>v!==id):[...x[key],id]}))}
 function setField(index:number,key:'canRead'|'canWrite',value:boolean){setForm(x=>({...x,fieldPermissions:x.fieldPermissions.map((f,i)=>i===index?{...f,[key]:value,...(key==='canRead'&&!value?{canWrite:false}:{})}:f)}))}
 async function save(e:FormEvent){e.preventDefault();if(!selected)return;setError('');setNotice('');try{await api(`/system/roles/${selected.id}/access`,{method:'PATCH',body:JSON.stringify(form)});setNotice('角色权限、数据范围和可视模块已生效；受影响用户需重新登录');await load();await open({...selected,...form,_count:selected._count})}catch(err){setError(err instanceof Error?err.message:'保存失败')}}
 async function create(e:FormEvent){e.preventDefault();setError('');try{const role=await api<Role>('/system/roles',{method:'POST',body:JSON.stringify(newRole)});setCreating(false);setNewRole({code:'',name:'',description:'',dataScope:'SELF'});await load();await open({...role,_count:{users:0}})}catch(err){setError(err instanceof Error?err.message:'创建失败')}}
 return <AppShell title="角色与访问控制" subtitle="每个角色统一配置功能权限、数据范围、字段权限和可见模块。">
  <div className="system-summary"><article><small>角色数量</small><b>{roles.length}</b><span>标准角色与自定义角色</span></article><article><small>权限点</small><b>{options.permissions.length}</b><span>服务端强制校验</span></article><article><small>可视模块</small><b>{options.menus.filter(x=>x.type==='MENU').length}</b><span>登录后按角色合并</span></article><article><small>数据范围</small><b>6</b><span>RBAC + Data Scope</span></article></div>
  <div className="crm-toolbar"><div><b>角色权限矩阵</b><p className="helper">点击角色查看和调整授权。一个用户拥有多个角色时，权限与菜单按并集计算。</p></div>{canManage&&<button className="primary" onClick={()=>{setCreating(true);setSelected(undefined);setError('')}}>＋ 新建自定义角色</button>}</div>
  {error&&!selected&&!creating&&<div className="error block">{error}</div>}<div className="role-grid">{roles.map(role=><button onClick={()=>void open(role)} key={role.id}><span className={`role-state ${role.active?'active':'disabled'}`}/><div><b>{role.name}</b><small>{role.code}{role.isSystem?' · 系统角色':' · 自定义角色'}</small></div><em>{scopes[role.dataScope]}</em><strong>{role._count.users}<small>用户</small></strong><strong>{role._count.permissions??0}<small>权限</small></strong></button>)}</div>
  {creating&&<div className="drawer-mask" onMouseDown={close}><section className="drawer access-drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">CUSTOM ROLE</p><h2>新建自定义角色</h2>{error&&<div className="error block">{error}</div>}<form className="access-form" onSubmit={create}><label>角色代码<input required pattern="[A-Z][A-Z0-9_]*" value={newRole.code} onChange={e=>setNewRole({...newRole,code:e.target.value.toUpperCase()})} placeholder="例如 REGIONAL_MANAGER"/></label><label>角色名称<input required value={newRole.name} onChange={e=>setNewRole({...newRole,name:e.target.value})}/></label><label>默认数据范围<select value={newRole.dataScope} onChange={e=>setNewRole({...newRole,dataScope:e.target.value})}>{Object.entries(scopes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>说明<textarea value={newRole.description} onChange={e=>setNewRole({...newRole,description:e.target.value})}/></label><button className="primary wide">创建后配置权限</button></form></section></div>}
  {selected&&<div className="drawer-mask" onMouseDown={close}><section className="drawer role-drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">{selected.code} · {selected.isSystem?'SYSTEM ROLE':'CUSTOM ROLE'}</p><h2>{selected.name}访问策略</h2>{notice&&<div className="success block">{notice}</div>}{error&&<div className="error block">{error}</div>}<form className="role-access-form" onSubmit={save}>
   <div className="form-grid"><label>角色名称<input value={form.name} disabled={!canManage} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>角色状态<select value={form.active?'1':'0'} disabled={!canManage||selected.code==='OWNER'} onChange={e=>setForm({...form,active:e.target.value==='1'})}><option value="1">启用</option><option value="0">停用</option></select></label><label>数据范围<select value={form.dataScope} disabled={!canManage||selected.code==='OWNER'} onChange={e=>setForm({...form,dataScope:e.target.value})}>{Object.entries(scopes).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>角色说明<input value={form.description} disabled={!canManage} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>
   {form.dataScope==='CUSTOM'&&<section className="access-section"><h3>指定组织范围</h3><div className="choice-grid">{options.orgUnits.map(unit=><label className={form.customOrgUnitIds.includes(unit.id)?'checked':''} key={unit.id}><input type="checkbox" checked={form.customOrgUnitIds.includes(unit.id)} disabled={!canManage} onChange={()=>toggle('customOrgUnitIds',unit.id)}/><b>{unit.name}</b><small>{unit.path}</small></label>)}</div></section>}
   <section className="access-section"><h3>可视模块</h3><p className="helper">决定此角色登录后能在侧栏看到哪些工作中心；接口仍由下方功能权限独立保护。</p><div className="menu-choice-grid">{options.menus.filter(x=>x.path).map(menu=><label className={form.menuIds.includes(menu.id)?'checked':''} key={menu.id}><input type="checkbox" checked={form.menuIds.includes(menu.id)} disabled={!canManage} onChange={()=>toggle('menuIds',menu.id)}/><b>{menu.name}</b><small>{menu.path}</small></label>)}</div></section>
   <section className="access-section"><h3>功能权限</h3><div className="permission-groups">{permissionGroups.map(([resource,items])=><article key={resource}><header><b>{resource}</b><button type="button" disabled={!canManage} onClick={()=>setForm(x=>({...x,permissionIds:[...new Set([...x.permissionIds,...items.map(p=>p.id)])]}))}>全选</button></header>{items.map(p=><label key={p.id}><input type="checkbox" checked={form.permissionIds.includes(p.id)} disabled={!canManage} onChange={()=>toggle('permissionIds',p.id)}/><span>{p.name}<small>{p.code}</small></span></label>)}</article>)}</div></section>
   <section className="access-section"><h3>字段权限</h3><p className="helper">敏感字段分别控制可读与可写；取消“可读”会自动取消“可写”。</p><div className="field-permission-table"><header><span>字段</span><span>读取</span><span>写入</span></header>{form.fieldPermissions.map((field,index)=>{const meta=options.fieldCatalog.find(x=>x.resource===field.resource&&x.field===field.field);return <div key={`${field.resource}.${field.field}`}><span><b>{meta?.label??field.field}</b><small>{field.resource}.{field.field}</small></span><input type="checkbox" checked={field.canRead} disabled={!canManage} onChange={e=>setField(index,'canRead',e.target.checked)}/><input type="checkbox" checked={field.canWrite} disabled={!canManage||!field.canRead} onChange={e=>setField(index,'canWrite',e.target.checked)}/></div>})}</div></section>
   {canManage&&<button className="primary sticky-save">保存全部访问策略</button>}
  </form></section></div>}
 </AppShell>
}
