import { AfterSalesPriority, AfterSalesStatus, AfterSalesType, ShipmentStatus } from '@ffai/database';
import { Type } from 'class-transformer';
import { IsArray, IsDateString, IsEnum, IsInt, IsNumber, IsOptional, IsString, Max, MaxLength, Min, MinLength, ValidateNested } from 'class-validator';

export class FulfillmentListQueryDto { @IsOptional() @Type(() => Number) @IsInt() @Min(1) page=1; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) pageSize=20; @IsOptional() @IsString() @MaxLength(100) keyword?:string; @IsOptional() @IsEnum(ShipmentStatus) shipmentStatus?:ShipmentStatus; @IsOptional() @IsEnum(AfterSalesStatus) afterSalesStatus?:AfterSalesStatus; }
export class ShipmentItemDto { @IsString() salesOrderItemId!:string; @IsString() stockLocationId!:string; @Type(()=>Number) @IsNumber() @Min(.001) quantity!:number; }
export class CreateShipmentDto { @IsString() salesOrderId!:string; @IsArray() @ValidateNested({each:true}) @Type(()=>ShipmentItemDto) items!:ShipmentItemDto[]; @IsOptional() @IsString() assignedToId?:string; @IsOptional() @IsString() @MaxLength(120) carrier?:string; @IsOptional() @IsString() @MaxLength(120) trackingNo?:string; @IsOptional() @IsString() @MaxLength(50) vehicleNo?:string; @IsOptional() @IsString() @MaxLength(100) driverName?:string; @IsOptional() @IsString() @MaxLength(30) driverPhone?:string; @IsOptional() @IsString() @MaxLength(500) deliveryAddress?:string; @IsOptional() @IsString() @MaxLength(100) contactName?:string; @IsOptional() @IsString() @MaxLength(30) contactPhone?:string; @IsOptional() @IsDateString() scheduledAt?:string; @IsOptional() @IsString() @MaxLength(1000) notes?:string; }
export class DeliverShipmentDto { @IsString() @MinLength(1) @MaxLength(100) signedBy!:string; @IsOptional() @IsArray() @IsString({each:true}) proofAttachmentIds?:string[]; @IsOptional() @IsString() @MaxLength(1000) note?:string; }
export class CreateInstallationDto { @IsString() shipmentId!:string; @IsOptional() @IsString() assignedToId?:string; @IsOptional() @IsDateString() scheduledStartAt?:string; @IsOptional() @IsDateString() scheduledEndAt?:string; @IsOptional() @IsString() @MaxLength(1000) notes?:string; }
export class ScheduleInstallationDto { @IsOptional() @IsString() assignedToId?:string; @IsDateString() scheduledStartAt!:string; @IsOptional() @IsDateString() scheduledEndAt?:string; }
export class CompleteInstallationDto { @IsString() @MinLength(1) @MaxLength(3000) completionNote!:string; @IsOptional() @IsArray() @IsString({each:true}) proofAttachmentIds?:string[]; }
export class CreateAfterSalesDto { @IsString() salesOrderId!:string; @IsEnum(AfterSalesType) type!:AfterSalesType; @IsOptional() @IsEnum(AfterSalesPriority) priority?:AfterSalesPriority; @IsString() @MinLength(1) @MaxLength(180) title!:string; @IsString() @MinLength(1) @MaxLength(5000) description!:string; @IsOptional() @IsArray() @IsString({each:true}) attachmentIds?:string[]; }
export class UpdateAfterSalesDto { @IsEnum(AfterSalesStatus) status!:AfterSalesStatus; @IsOptional() @IsString() assignedToId?:string; @IsOptional() @IsString() @MaxLength(5000) resolution?:string; }
export class AddAfterSalesCommentDto { @IsString() @MinLength(1) @MaxLength(5000) content!:string; @IsOptional() internal?:boolean; }
